// Mood of Wood — Staff Pilot — centralized department navigation config.
//
// This is Phase 1 of the department/Management-Control-Tower rollout:
// navigation, page structure, dashboard shells, and access — NOT the full
// operational workflow for every department (that is Phase 2, module by
// module). Nothing here invents data; every dashboard reads real rows from
// the existing `departments`, `staff_tasks`, `bridges`, and `user_profiles`
// tables, scoped by the SAME Postgres RLS policies already protecting them.
//
// Keyed by the existing `departments.code` values already seeded in the
// live database (see supabase — department_groups/departments). This file
// does not create or duplicate that data; it only maps each existing code
// to a route, an icon, and the Phase-2 function-card list from the rollout
// spec. Department display names (English/Gujarati) always come from the
// `departments` row itself (name_en/name_gu), never duplicated here, so the
// UI can never drift from the database.

// DB `departments.code` -> app route path. Every path below matches the
// route list from the rollout spec exactly.
export const DEPARTMENT_ROUTES = {
  CONTROL_TOWER: "/management",
  RETAIL: "/retail",
  FRANCHISE: "/franchise-dealer",
  MARKETING: "/marketing",
  ECOMMERCE: "/ecommerce",
  INTERIOR: "/interior-projects",
  B2B_B2G: "/b2b-b2g",
  PROCUREMENT: "/procurement",
  GODOWN_INV: "/inventory",
  DISPATCH: "/dispatch",
  FACTORY: "/factory",
  RND: "/product-rnd",
  HR_ADMIN: "/hr-admin",
  ACCOUNTS: "/accounts-finance",
  CUST_SERVICE: "/customer-service",
};

// Sidebar / Control-Tower display order. Management Control Tower always
// first, matching the sidebar requirement.
export const DEPARTMENT_ORDER = [
  "CONTROL_TOWER",
  "RETAIL",
  "FRANCHISE",
  "MARKETING",
  "ECOMMERCE",
  "INTERIOR",
  "B2B_B2G",
  "PROCUREMENT",
  "GODOWN_INV",
  "DISPATCH",
  "FACTORY",
  "RND",
  "HR_ADMIN",
  "ACCOUNTS",
  "CUST_SERVICE",
];

export const DEPARTMENT_ICONS = {
  CONTROL_TOWER: "🗼",
  RETAIL: "🏬",
  FRANCHISE: "🤝",
  MARKETING: "📣",
  ECOMMERCE: "🛒",
  INTERIOR: "🛋️",
  B2B_B2G: "🏛️",
  PROCUREMENT: "🧾",
  GODOWN_INV: "📦",
  DISPATCH: "🚚",
  FACTORY: "🏭",
  RND: "🔬",
  HR_ADMIN: "🧑‍💼",
  ACCOUNTS: "💰",
  CUST_SERVICE: "🎧",
};

// Fallback bilingual labels — used ONLY if a department row is missing
// name_en/name_gu for some reason (should not normally happen since both
// columns are NOT NULL). The department row from the database is always
// preferred at render time.
export const DEPARTMENT_LABEL_FALLBACK = {
  CONTROL_TOWER: { en: "Management Control Tower", gu: "મેનેજમેન્ટ કંટ્રોલ ટાવર" },
  RETAIL: { en: "Retail Stores", gu: "રિટેલ સ્ટોર્સ" },
  FRANCHISE: { en: "Franchise/Dealer", gu: "ફ્રેન્ચાઇઝી અને ડીલર" },
  MARKETING: { en: "Marketing", gu: "માર્કેટિંગ" },
  ECOMMERCE: { en: "E-commerce", gu: "ઈ-કોમર્સ" },
  INTERIOR: { en: "Interior Projects", gu: "ઇન્ટિરિયર પ્રોજેક્ટ્સ" },
  B2B_B2G: { en: "B2B/B2G", gu: "બીટુબી અને બીટુજી" },
  PROCUREMENT: { en: "Procurement", gu: "ખરીદી વિભાગ" },
  GODOWN_INV: { en: "Godown/Inventory", gu: "ગોડાઉન અને ઇન્વેન્ટરી" },
  DISPATCH: { en: "Dispatch/Logistics", gu: "ડિસ્પેચ અને લોજિસ્ટિક્સ" },
  FACTORY: { en: "Factory/Manufacturing", gu: "ફેક્ટરી અને મેન્યુફેક્ચરિંગ" },
  RND: { en: "Product Design/R&D", gu: "પ્રોડક્ટ ડિઝાઇન અને આર એન્ડ ડી" },
  HR_ADMIN: { en: "HR/Admin", gu: "એચઆર અને એડમિન" },
  ACCOUNTS: { en: "Accounts/Finance", gu: "એકાઉન્ટ્સ અને ફાઇનાન્સ" },
  CUST_SERVICE: { en: "Customer Service", gu: "કસ્ટમર સર્વિસ" },
};

// Function cards per department, from the rollout spec. Every card is
// Phase 2 in this release (no fabricated functionality) — the generic
// task/Bridge system already live in the app (Today's Tasks / Assign Task /
// Bridges) is surfaced separately as Quick Actions on each dashboard, since
// it is the one piece of real, working functionality every department can
// already use today.
function cards(...pairs) {
  return pairs.map(([en, gu]) => ({ en, gu }));
}

export const DEPARTMENT_FUNCTION_CARDS = {
  RETAIL: cards(
    ["Walk-in Leads & CRM", "વોક-ઇન લીડ્સ અને સીઆરએમ"],
    ["Sales & Quotations", "વેચાણ અને ભાવપત્રક"],
    ["Order Booking", "ઓર્ડર બુકિંગ"],
    ["Payment Follow-up", "ચુકવણી ફોલો-અપ"],
    ["Display & Visual Merchandising", "ડિસ્પ્લે અને વિઝ્યુઅલ મર્ચેન્ડાઇઝિંગ"],
    ["Store Operations", "સ્ટોર ઓપરેશન્સ"],
    ["Stock Availability", "સ્ટોક ઉપલબ્ધતા"],
    ["Stock Transfer Requests", "સ્ટોક ટ્રાન્સફર વિનંતીઓ"],
    ["Delivery Coordination", "ડિલિવરી સંકલન"],
    ["Complaints & Service", "ફરિયાદો અને સેવા"],
    ["Sales Targets", "વેચાણ લક્ષ્યાંક"],
    ["Sales Performance", "વેચાણ કામગીરી"],
  ),
  FRANCHISE: cards(
    ["Franchise Leads", "ફ્રેન્ચાઇઝી લીડ્સ"],
    ["Lead Qualification", "લીડ ક્વોલિફિકેશન"],
    ["Location Study", "સ્થળ અભ્યાસ"],
    ["Proposal & Investment", "પ્રસ્તાવ અને રોકાણ"],
    ["Agreement & Territory", "કરાર અને ટેરિટરી"],
    ["Dealer Onboarding", "ડીલર ઓનબોર્ડિંગ"],
    ["Store Setup", "સ્ટોર સેટઅપ"],
    ["Product Selection", "પ્રોડક્ટ પસંદગી"],
    ["Dealer Orders", "ડીલર ઓર્ડર"],
    ["Pricing & Discounts", "કિંમત અને ડિસ્કાઉન્ટ"],
    ["Training & Support", "તાલીમ અને સપોર્ટ"],
    ["Targets & Outstanding", "લક્ષ્યાંક અને બાકી રકમ"],
  ),
  MARKETING: cards(
    ["Marketing Calendar", "માર્કેટિંગ કેલેન્ડર"],
    ["Campaigns", "કેમ્પેઇન"],
    ["Content Planning", "કન્ટેન્ટ પ્લાનિંગ"],
    ["Graphics & Copy", "ગ્રાફિક્સ અને કોપી"],
    ["Photography & Video", "ફોટોગ્રાફી અને વિડિયો"],
    ["Social Media", "સોશિયલ મીડિયા"],
    ["Meta Ads", "મેટા જાહેરાતો"],
    ["Google Ads", "ગૂગલ જાહેરાતો"],
    ["Lead Sources", "લીડ સ્ત્રોત"],
    ["Campaign Budget", "કેમ્પેઇન બજેટ"],
    ["CPL & ROI", "સીપીએલ અને આરઓઆઈ"],
    ["Events & BNI", "ઇવેન્ટ્સ અને બીએનઆઈ"],
    ["Footfall Tracking", "ફૂટફોલ ટ્રેકિંગ"],
  ),
  ECOMMERCE: cards(
    ["Product Catalogue", "પ્રોડક્ટ કેટલોગ"],
    ["Product Images", "પ્રોડક્ટ છબીઓ"],
    ["Pricing & Offers", "કિંમત અને ઓફર્સ"],
    ["Inventory Sync", "ઇન્વેન્ટરી સિંક"],
    ["Online Orders", "ઓનલાઇન ઓર્ડર"],
    ["Online Payments", "ઓનલાઇન ચુકવણી"],
    ["Fulfilment", "ફુલફિલમેન્ટ"],
    ["Courier Tracking", "કુરિયર ટ્રેકિંગ"],
    ["Returns", "રિટર્ન"],
    ["Cancellations", "કેન્સલેશન"],
    ["Refunds", "રિફંડ"],
    ["Online Support", "ઓનલાઇન સપોર્ટ"],
    ["Reviews", "સમીક્ષાઓ"],
    ["Conversion", "કન્વર્ઝન"],
    ["Abandoned Carts", "છોડેલી કાર્ટ"],
    ["Reconciliation", "રિકન્સિલિએશન"],
  ),
  INTERIOR: cards(
    ["Quotation", "ભાવપત્રક"],
    ["Deal Closure", "ડીલ ક્લોઝર"],
    ["Design", "ડિઝાઇન"],
    ["Design Approval", "ડિઝાઇન મંજૂરી"],
    ["Design Lock", "ડિઝાઇન લોક"],
    ["Drawings", "ડ્રોઈંગ"],
    ["Site Execution", "સાઇટ એક્ઝિક્યુશન"],
    ["Daily Updates", "દૈનિક અપડેટ"],
    ["Material Requirements", "સામગ્રી જરૂરિયાત"],
    ["Purchase Coordination", "ખરીદી સંકલન"],
    ["Project Timeline", "પ્રોજેક્ટ ટાઇમલાઇન"],
    ["Client Communication", "ક્લાયન્ટ કમ્યુનિકેશન"],
    ["Payment Follow-up", "ચુકવણી ફોલો-અપ"],
    ["Project Completion", "પ્રોજેક્ટ પૂર્ણતા"],
  ),
  B2B_B2G: cards(
    ["Lead & Enquiry", "લીડ અને પૂછપરછ"],
    ["Tender/GEM", "ટેન્ડર/GEM"],
    ["Requirement", "જરૂરિયાત"],
    ["Site Survey", "સાઇટ સર્વે"],
    ["BOQ", "BOQ"],
    ["Estimation", "અંદાજ"],
    ["Quotation", "ભાવપત્રક"],
    ["Tender Submission", "ટેન્ડર સબમિશન"],
    ["Negotiation", "વાટાઘાટ"],
    ["Agreement", "કરાર"],
    ["EMD/Security Deposit", "EMD/સિક્યોરિટી ડિપોઝિટ"],
    ["Design/Sample Approval", "ડિઝાઇન/નમૂના મંજૂરી"],
    ["Execution", "એક્ઝિક્યુશન"],
    ["Dispatch", "ડિસ્પેચ"],
    ["Billing", "બિલિંગ"],
    ["Documentation", "દસ્તાવેજીકરણ"],
    ["Collection Follow-up", "કલેક્શન ફોલો-અપ"],
  ),
  PROCUREMENT: cards(
    ["Purchase Requirements", "ખરીદી જરૂરિયાત"],
    ["BOQ Verification", "BOQ ચકાસણી"],
    ["Raw Material Procurement", "કાચી સામગ્રી ખરીદી"],
    ["Finished Goods Procurement", "તૈયાર માલ ખરીદી"],
    ["Vendor Job Work", "વેન્ડર જોબ વર્ક"],
    ["Material Procurement", "સામગ્રી ખરીદી"],
    ["Labour Procurement", "મજૂર ખરીદી"],
    ["Turnkey Agency", "ટર્નકી એજન્સી"],
    ["Vendor Quotations", "વેન્ડર ભાવપત્રક"],
    ["Vendor Comparison", "વેન્ડર સરખામણી"],
    ["Purchase Orders", "ખરીદી ઓર્ડર"],
    ["Work Orders", "વર્ક ઓર્ડર"],
    ["Approvals", "મંજૂરીઓ"],
    ["Vendor Follow-up", "વેન્ડર ફોલો-અપ"],
    ["Vendor Dispatch", "વેન્ડર ડિસ્પેચ"],
    ["GRN Coordination", "GRN સંકલન"],
    ["Rejections", "નકારેલ"],
    ["Payment Coordination", "ચુકવણી સંકલન"],
    ["Emergency Procurement", "કટોકટી ખરીદી"],
  ),
  GODOWN_INV: cards(
    ["Goods Receipt", "માલ પ્રાપ્તિ"],
    ["GRN", "GRN"],
    ["Incoming QC", "આવક QC"],
    ["Product Master", "પ્રોડક્ટ માસ્ટર"],
    ["Product Photos", "પ્રોડક્ટ ફોટા"],
    ["Barcode/QR", "બારકોડ/QR"],
    ["Rack Location", "રેક સ્થાન"],
    ["Stock Transfers", "સ્ટોક ટ્રાન્સફર"],
    ["Stock Reservation", "સ્ટોક રિઝર્વેશન"],
    ["Raw Materials", "કાચી સામગ્રી"],
    ["Factory Store", "ફેક્ટરી સ્ટોર"],
    ["Finished Goods", "તૈયાર માલ"],
    ["Display Stock", "ડિસ્પ્લે સ્ટોક"],
    ["WIP", "WIP"],
    ["Site Stock", "સાઇટ સ્ટોક"],
    ["In-transit Stock", "ટ્રાન્ઝિટ સ્ટોક"],
    ["Damaged Stock", "ક્ષતિગ્રસ્ત સ્ટોક"],
    ["Rejected Stock", "નકારેલ સ્ટોક"],
    ["Repair Stock", "રિપેર સ્ટોક"],
    ["Scrap", "સ્ક્રેપ"],
    ["Physical Audit", "ફિઝિકલ ઓડિટ"],
    ["Stock Ageing", "સ્ટોક એજિંગ"],
    ["Stock Variance", "સ્ટોક વેરિયન્સ"],
  ),
  DISPATCH: cards(
    ["Delivery Planning", "ડિલિવરી પ્લાનિંગ"],
    ["Stock Check", "સ્ટોક ચેક"],
    ["Payment Check", "ચુકવણી ચેક"],
    ["Site Readiness", "સાઇટ તૈયારી"],
    ["Picking", "પિકિંગ"],
    ["Packing", "પેકિંગ"],
    ["Pre-dispatch QC", "પ્રી-ડિસ્પેચ QC"],
    ["Mandatory DC Checklist", "ફરજિયાત DC ચેકલિસ્ટ"],
    ["Barcode Scan", "બારકોડ સ્કેન"],
    ["Goods Issue", "ગુડ્સ ઇશ્યૂ"],
    ["Delivery Challan", "ડિલિવરી ચલણ"],
    ["Invoice", "ઇન્વોઇસ"],
    ["E-way Bill", "ઈ-વે બિલ"],
    ["Transporter", "ટ્રાન્સપોર્ટર"],
    ["Vehicle", "વાહન"],
    ["In-transit Tracking", "ટ્રાન્ઝિટ ટ્રેકિંગ"],
    ["Delivery Confirmation", "ડિલિવરી પુષ્ટિ"],
    ["POD", "POD"],
    ["Installation", "ઇન્સ્ટોલેશન"],
    ["Failed Delivery", "નિષ્ફળ ડિલિવરી"],
    ["Customer Happiness", "ગ્રાહક ખુશી"],
  ),
  FACTORY: cards(
    ["Production Planning", "ઉત્પાદન આયોજન"],
    ["Job Orders", "જોબ ઓર્ડર"],
    ["BOM", "BOM"],
    ["Cutting Lists", "કટિંગ લિસ્ટ"],
    ["Drawings", "ડ્રોઈંગ"],
    ["Raw Material Availability", "કાચી સામગ્રી ઉપલબ્ધતા"],
    ["Material Issue", "સામગ્રી ઇશ્યૂ"],
    ["Machine Tracking", "મશીન ટ્રેકિંગ"],
    ["WIP Stages", "WIP તબક્કા"],
    ["Worker Productivity", "કામદાર ઉત્પાદકતા"],
    ["Shift Productivity", "શિફ્ટ ઉત્પાદકતા"],
    ["In-process QC", "ઇન-પ્રોસેસ QC"],
    ["Final QC", "ફાઇનલ QC"],
    ["Rework", "રિવર્ક"],
    ["Rejection", "નકારેલ"],
    ["Wastage", "બગાડ"],
    ["Finished Goods", "તૈયાર માલ"],
    ["Packing", "પેકિંગ"],
    ["Transfer", "ટ્રાન્સફર"],
    ["Product Time Tracking", "પ્રોડક્ટ સમય ટ્રેકિંગ"],
    ["Mandatory Product Costing", "ફરજિયાત પ્રોડક્ટ કોસ્ટિંગ"],
    ["Factory Inventory Costing", "ફેક્ટરી ઇન્વેન્ટરી કોસ્ટિંગ"],
  ),
  RND: cards(
    ["Trend Research", "ટ્રેન્ડ સંશોધન"],
    ["Competitor Research", "સ્પર્ધક સંશોધન"],
    ["Product Ideas", "પ્રોડક્ટ આઈડિયા"],
    ["Design Brief", "ડિઝાઇન બ્રીફ"],
    ["Sketches", "સ્કેચ"],
    ["Drawings", "ડ્રોઈંગ"],
    ["3D Design", "3D ડિઝાઇન"],
    ["Materials", "સામગ્રી"],
    ["Finishes", "ફિનિશ"],
    ["Hardware", "હાર્ડવેર"],
    ["Prototype", "પ્રોટોટાઇપ"],
    ["Sample", "નમૂનો"],
    ["Costing", "કોસ્ટિંગ"],
    ["Feasibility", "શક્યતા"],
    ["Testing", "ટેસ્ટિંગ"],
    ["QC", "QC"],
    ["Improvement", "સુધારો"],
    ["Management Approval", "મેનેજમેન્ટ મંજૂરી"],
    ["Design Freeze", "ડિઝાઇન ફ્રીઝ"],
    ["BOM", "BOM"],
    ["Product Master", "પ્રોડક્ટ માસ્ટર"],
    ["Product Launch", "પ્રોડક્ટ લોન્ચ"],
    ["Feedback", "પ્રતિભાવ"],
    ["Revisions", "રિવિઝન"],
  ),
  HR_ADMIN: cards(
    ["Manpower Planning", "મેનપાવર પ્લાનિંગ"],
    ["Recruitment", "ભરતી"],
    ["Interviews", "ઇન્ટરવ્યુ"],
    ["Selection", "પસંદગી"],
    ["Offers", "ઓફર"],
    ["Onboarding", "ઓનબોર્ડિંગ"],
    ["Employee Documents", "કર્મચારી દસ્તાવેજો"],
    ["Attendance", "હાજરી"],
    ["Shifts", "શિફ્ટ"],
    ["Leave", "રજા"],
    ["Payroll Inputs", "પેરોલ ઇનપુટ"],
    ["Roles & Responsibilities", "ભૂમિકાઓ અને જવાબદારીઓ"],
    ["SOPs", "SOP"],
    ["Permissions", "પરવાનગીઓ"],
    ["Employee Targets", "કર્મચારી લક્ષ્યાંક"],
    ["Performance", "કામગીરી"],
    ["Training", "તાલીમ"],
    ["Skill Development", "કૌશલ્ય વિકાસ"],
    ["Company Assets", "કંપની સંપત્તિ"],
    ["Administration", "એડમિનિસ્ટ્રેશન"],
    ["Discipline", "શિસ્ત"],
    ["Exit", "એક્ઝિટ"],
    ["Full & Final", "ફુલ એન્ડ ફાઇનલ"],
  ),
  ACCOUNTS: cards(
    ["Sales Billing", "વેચાણ બિલિંગ"],
    ["Receipts", "રસીદો"],
    ["Purchase Bills", "ખરીદી બિલ"],
    ["Payables", "ચૂકવવાપાત્ર"],
    ["Collection Follow-up", "કલેક્શન ફોલો-અપ"],
    ["Receivable Ageing", "પ્રાપ્તિ એજિંગ"],
    ["Supplier Payments", "સપ્લાયર ચુકવણી"],
    ["Agency Payments", "એજન્સી ચુકવણી"],
    ["Payment Approvals", "ચુકવણી મંજૂરીઓ"],
    ["Cash Position", "રોકડ સ્થિતિ"],
    ["Bank Position", "બેંક સ્થિતિ"],
    ["Fund Position", "ફંડ સ્થિતિ"],
    ["Cash Forecast", "રોકડ આગાહી"],
    ["Expenses", "ખર્ચ"],
    ["Budgets", "બજેટ"],
    ["Cost Centres", "કોસ્ટ સેન્ટર"],
    ["Order Costing", "ઓર્ડર કોસ્ટિંગ"],
    ["Project Costing", "પ્રોજેક્ટ કોસ્ટિંગ"],
    ["Gross Profit", "ગ્રોસ પ્રોફિટ"],
    ["Department P&L", "વિભાગ P&L"],
    ["Branch P&L", "શાખા P&L"],
    ["Company P&L", "કંપની P&L"],
    ["GST", "GST"],
    ["Tax", "ટેક્સ"],
    ["Payroll", "પેરોલ"],
    ["Audit", "ઓડિટ"],
    ["Tally Automation", "ટેલી ઓટોમેશન"],
    ["EMI Planning", "EMI પ્લાનિંગ"],
    ["Salary Planning", "પગાર આયોજન"],
  ),
  CUST_SERVICE: cards(
    ["Complaint Tickets", "ફરિયાદ ટિકિટ"],
    ["Complaint Category", "ફરિયાદ કેટેગરી"],
    ["Priority", "પ્રાધાન્ય"],
    ["Department Assignment", "વિભાગ સોંપણી"],
    ["Responsible Person", "જવાબદાર વ્યક્તિ"],
    ["Call Schedule", "કોલ શેડ્યૂલ"],
    ["Visit Schedule", "મુલાકાત શેડ્યૂલ"],
    ["Investigation", "તપાસ"],
    ["Action Required", "જરૂરી ક્રિયા"],
    ["Spare/Material", "સ્પેર/સામગ્રી"],
    ["Technician", "ટેકનિશિયન"],
    ["SLA", "SLA"],
    ["Ageing", "એજિંગ"],
    ["Escalation", "એસ્કેલેશન"],
    ["Repair", "રિપેર"],
    ["Service Completion", "સેવા પૂર્ણતા"],
    ["Customer Confirmation", "ગ્રાહક પુષ્ટિ"],
    ["Closure Proof", "ક્લોઝર પુરાવો"],
    ["Feedback", "પ્રતિભાવ"],
    ["Google Review", "ગૂગલ સમીક્ષા"],
    ["Repeat Complaint", "પુનરાવર્તિત ફરિયાદ"],
    ["Visit Pending", "મુલાકાત બાકી"],
    ["Vendor Pending", "વેન્ડર બાકી"],
  ),
};

export function getDepartmentRoute(code) {
  return DEPARTMENT_ROUTES[code] || null;
}

export function getDepartmentIcon(code) {
  return DEPARTMENT_ICONS[code] || "🏢";
}

export function getDepartmentCards(code) {
  return DEPARTMENT_FUNCTION_CARDS[code] || [];
}

// Ordered, route-mapped department list built from whatever the database
// actually returned (never invented) — departments without a known code
// mapping are dropped rather than shown with a broken link.
export function buildOrderedDepartments(departments) {
  const byCode = new Map((departments || []).map((d) => [d.code, d]));
  return DEPARTMENT_ORDER.filter((code) => byCode.has(code) && DEPARTMENT_ROUTES[code]).map((code) => ({
    ...byCode.get(code),
    route: DEPARTMENT_ROUTES[code],
    icon: DEPARTMENT_ICONS[code],
  }));
}
